language: perl
sudo: false

cache:
  directories:
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - cpanm --notest --quiet Dist::Zilla
    - dzil authordeps | cpanm --quiet --notest
    - cpanm --quiet --notest --installdeps .

script:
    - dzil test
